name: "auto-release"
on:
  workflow_call:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-auto-release@0d52315ead13f5f739cc864ec806c28a8a70b0d5 # v2
        with:
          publish: false
