name: "auto-release"
on:
  workflow_call:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-auto-release@725f1601ce164d51f2c1c19055126aef267fd08e # v4
        with:
          publish: false
