name: "auto-release"
on:
  workflow_call:

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: cloudposse/github-action-auto-release@3064115aec049f3f56d0f8860db302ecd820298c # v3
        with:
          publish: false
