# example 1: on push to master
name: Bump version
on:
  workflow_call:
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # v1 # Don't use @master or @v1 unless you're happy to test the latest version
      id: tag_version
      env:
        GITHUB_TOKEN: ${{ secrets.token }} 
        TAG_PREFIX: v

    - name: Create a GitHub release
      uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1
      with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          generateReleaseNotes: true
