name: Publish Development Helm Charts
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Helm
        uses: mamezou-tech/setup-helmfile@v1.0.0
        with:
          helm-version: "v3.10.1"

      - name: Package and Publish
        run: bash .github/workflows/deploy.sh
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GLUEOPS_ENV: "development"
