name: Publish Development Helm Charts

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Helm
        uses: mamezou-tech/setup-helmfile@v1.0.0
        with:
          helm-version: "v3.10.1"

      - name: Package and Publish
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          GLUEOPS_ENV: "development"
          group: "platform"
        run: |
          export AWS_REGION=us-west-2
          
          status_code=`curl -s -o /dev/null -I -w "%{http_code}" https://${S3_BUCKET_NAME}.s3.us-west-2.amazonaws.com/${group}/index.yaml`
          if [ "$status_code" == "404" ]; then
              helm s3 init s3://$S3_BUCKET_NAME/$group
          fi
          
          helm repo add $group s3://$S3_BUCKET_NAME/$group

          helm package --dependency-update .

          for F in $(ls -f *.tgz); do
              if [ "$GLUEOPS_ENV" == "development" ]; then
                  helm s3 push --acl="public-read" --relative $F $group --force
              fi

              if [ "$GLUEOPS_ENV" == "production" ]; then
                  helm s3 push --acl="public-read" --relative $F $group --ignore-if-exists
              fi

          done


