name: Publish Development Helm Charts

on:
  workflow_call:



jobs:
  publish:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.GLUEOPS_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        
      - name: Install Helm Docs
        uses: envoy/install-helm-docs@05313083ef2cfaea27c4c3d7cb725242d22ea88b # v1.0.0
        with:
          version: 1.12.0
      
      - name: Generate and Commit helm-docs
        run: |
          echo '{{ template "chart.header" . }}
          {{ template "chart.deprecationWarning" . }}

          {{ template "chart.badgesSection" . }}

          {{ template "chart.description" . }}

          {{ template "chart.homepageLine" . }}

          {{ template "chart.maintainersSection" . }}

          {{ template "chart.sourcesSection" . }}

          {{ template "chart.requirementsSection" . }}

          {{ template "chart.valuesSection" . }}' > README.md.gotmpl
          helm-docs -t README.md.gotmpl
          git config --global user.email "github@glueops.dev"
          git config --global user.name "GlueOps"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "docs: automated helm-docs action"
            git push
          else
            echo "No changes detected. Nothing to commit."
          fi

