name: Publish Development Helm Charts

on:
  workflow_call:
    inputs:
      GLUEOPS_ENV:
        required: true
        type: string
      HELM_CHART_REPO_NAME:
        required: true
        type: string


jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.GLUEOPS_ENV }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install Helm Docs
        uses: envoy/install-helm-docs@v1.0.0
        with:
          version: 1.11.0
      

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Helm
        uses: mamezou-tech/setup-helmfile@v1.0.0
        with:
          helm-version: "v3.10.1"

      - name: Package and Publish
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          HELM_CHART_REPO_NAME: ${{ inputs.HELM_CHART_REPO_NAME }}
        run: |
          export AWS_REGION=us-west-2
          
          status_code=`curl -s -o /dev/null -I -w "%{http_code}" https://${S3_BUCKET_NAME}.s3.us-west-2.amazonaws.com/${HELM_CHART_REPO_NAME}/index.yaml`
          if [ "$status_code" == "404" ]; then
              helm s3 init s3://$S3_BUCKET_NAME/$HELM_CHART_REPO_NAME
          fi
          
          helm repo add $HELM_CHART_REPO_NAME s3://$S3_BUCKET_NAME/$HELM_CHART_REPO_NAME

          helm package --dependency-update .

          for F in $(ls -f *.tgz); do

            helm s3 push --acl="public-read" --relative $F $HELM_CHART_REPO_NAME

          done

          helm s3 reindex --acl="public-read" --relative $HELM_CHART_REPO_NAME
